* <2022-05-24 k>

Van sok kaszó által mért kút (18 kút) ebből 4 db kontroll.
Excellben látszik, amit Zoli küldött. Kézi észlelés, heti egy adat.
Van hozzá csapadék is. Nedves vagy száraz év, esett vagy nem esett.

Cél az, hogy a vízvisszatartás pozitív hatását számszerűsítsük.

2014 21. hét az első oszlop. Milyen nap?

2021. 40. héttől kezdődik.

** Feladat
- [X] Kontroll kutakat idősorként ábrázolni. Négy év adata.
  2014-től heti mérések, a második munkalapon már feliratozott.
- [X] Kitalálni, hogy hogyan nézzük meg.
- [X] Tölgyes és égeres kontroll meg kell felezni.
- [ ] Kitalálni, hogy milyen elrendezést lehet ráhúzni.

* Differenciás
Azonos fafajjal azonos talajvízmélységgel rendelkező kontrollt választasz a kontroll időszakban (2014/40. héttől, két év múlváig két vegetációs időszak, két év)
. Megvan az Excelben, hogy melyiket melyikhez választották.

Utánna különbségeket képzek a kontroll kút és a beavatkozással érintett kút között. Amikor megvan, akkor van egy különbség idősorom. Két kút különbség idősora.

A beavatkozásos időszakban is meg kell csinálni ugyanezt. Ezzel a meteorológiai hatásokat kiejtetted. Mivel nem nagy távolságok, nagyjából ugyan az.
A vegetáció hatását kiejted, mert ugyan abból az állományból van. A talajvíz hatása is kiejtve, mert ugyan az a mélység.

Úgy lett belőle egy-egy oszlop, hogy vettek belőle egy átlagot.


Különbség idősor a kontroll és a különbségidősor a beavatkozásosban. Ott lehet hatással a beavatkozás típusa és a beavatkozás hatása.
A távolság is.

A különbség idősorokat lehet elemezni a távolsággal.

Van két időszak, nem csak az átlagait, hanem a térbeli idősoroknak az időbeli különbségét hasonítod össze.

Tavak hatása sokkan nagyobb, mint a logveirnek. Teljes időszakra és a vegetációs időszakra.

Különbség idősor, amin nincs beavatkozás, különbség idősor, amin van beavatkozás.

boxplotként a diagramban, ami tulajdonképpen a térbeli és időbeli különbségek átlaga.

Térbeli különbség kontrol vs. kezelés (de akkor még nincs kezelés)
Időbeli, amikor a térkbeli idősor különbségét vettem, akkor veszem a két eredmény különbségét.

Van róla rajz.
