* <2022-05-24 k>

Van sok kaszó által mért kút (18 kút) ebből 4 db kontroll.
Excellben látszik, amit Zoli küldött. Kézi észlelés, heti egy adat.
Van hozzá csapadék is. Nedves vagy száraz év, esett vagy nem esett.

Cél az, hogy a vízvisszatartás pozitív hatását számszerűsítsük.

2014 21. hét az első oszlop. Milyen nap?

2021. 40. héttől kezdődik.

** Feladat
- [X] Kontroll kutakat idősorként ábrázolni. Négy év adata.
  2014-től heti mérések, a második munkalapon már feliratozott.
- [X] Kitalálni, hogy hogyan nézzük meg.
- [X] Tölgyes és égeres kontroll meg kell felezni.
- [ ] Kitalálni, hogy milyen elrendezést lehet ráhúzni.

* Differenciás
Azonos fafajjal azonos talajvízmélységgel rendelkező kontrollt választasz a kontroll időszakban (2014/40. héttől, két év múlváig két vegetációs időszak, két év)
. Megvan az Excelben, hogy melyiket melyikhez választották.

Utánna különbségeket képzek a kontroll kút és a beavatkozással érintett kút között. Amikor megvan, akkor van egy különbség idősorom. Két kút különbség idősora.

A beavatkozásos időszakban is meg kell csinálni ugyanezt. Ezzel a meteorológiai hatásokat kiejtetted. Mivel nem nagy távolságok, nagyjából ugyan az.
A vegetáció hatását kiejted, mert ugyan abból az állományból van. A talajvíz hatása is kiejtve, mert ugyan az a mélység.

Úgy lett belőle egy-egy oszlop, hogy vettek belőle egy átlagot.


Különbség idősor a kontroll és a különbségidősor a beavatkozásosban. Ott lehet hatással a beavatkozás típusa és a beavatkozás hatása.
A távolság is.

A különbség idősorokat lehet elemezni a távolsággal.

Van két időszak, nem csak az átlagait, hanem a térbeli idősoroknak az időbeli különbségét hasonítod össze.

Tavak hatása sokkan nagyobb, mint a logveirnek. Teljes időszakra és a vegetációs időszakra.

Különbség idősor, amin nincs beavatkozás, különbség idősor, amin van beavatkozás.

boxplotként a diagramban, ami tulajdonképpen a térbeli és időbeli különbségek átlaga.

Térbeli különbség kontrol vs. kezelés (de akkor még nincs kezelés)
Időbeli, amikor a térkbeli idősor különbségét vettem, akkor veszem a két eredmény különbségét.

Van róla rajz.

* <2022-06-20 h>

** Idősor ábrák
- [X] Összes kontroll
- [X] Összes éger
- [X] Összes tölgy

** Differencia
Táblázat alapján, majd küldi.
Különbségek, kontroll/kezelés.

Különbségek boxplot ábra.
Két részben 2016-10-01 előtt és után.

* Kérdések
Távoli kutak (3&4) hol vannak az áttekintő ábráról. Kívül esnek a területen?
Jó-e a tábla?

* <2022-08-18 cs>
Csoportokba sorolt kutak.

- Kontroll
- Égeres
- Tölgyes

A számítás nem volt jó, az alapadatok jók voltak. Az Előd rosszból
vonogatott ki.

Idősorokból kell ábra. A csapadék idősort is rá kell tenni.
Az elején csinált András havi csapadékokat.

A kiinduló táblázatban van heti csapadékösszeg és
András megnézni, hogy mi van nálla. Kiss Katival letöltött
Boreas adatok?

A kút száma lehetne a közös hivatkozási alap.
Az Erdészettudomány Közlemények cikk alapján megnézni.

Koordináták a monitoring tervben. 3. fejezetben
Adatok/Kaszozrt/monitoring terv

Olyan plotokat kellene létrehozni

** Ábrák
*** Áttekintő
4-es ábra, ahol a kontroll és a többi csoportosan látszik.
4 ábra egymás mellett idősorosan.

*** Szemléltető ábra
Hasonló az Elődéhez szemléltető ábra. Hogyan lehetnek a különbségek.
Különböző színnel beszinezni a különbségeket a 2. ábrán.

*** Boxplot
Táblázatba szedni a boxplot adatait.

*** t-próba
t-próbával összehasonlítani a két adatsort.
Van-e szignifikáns különbség

*** Vegetációs időszakra
Csak a vegetációs időszakra.

Cseke Csabának a dolgozatában bent vannak a leürítések.

Okt1–Szept30 nemzetközi hidro év. Erre kell minden az ábrára!

Vegetációs időszak Április1–Szept30-ig.

*** Táblázat
Pontszám átlag, szórás, db.

* <2022-08-20 szo>
** Boxplothoz ötlet
Egy objektumba rakni minden adatot.
Esetleg összehasonlítható, ha nullába transzformálom az alapesetet.

* <2022-08-23 k>
A Control & Treatment különböző színű.

Jó ábra helye
/KOrabbi_anyagok_legbővebben_CsekeCsabaSzakdolgozat/Adat
ok/Kaszo_Elod_EGU2019joo/Plot.xlsx

Az a jó, ha feljebb van a kezelés boxplotja!

A kutakat a log weir és a reservoir alapján csoportosítani!

Kell egy olyan magyarázó ábra, ami a műveletet magyarázza.

Van napi csapadék.

** Kérdések
- [X] 4 részes idősor ábra csapadékkal, a nyers adatok bemutatására. Zolitól kérdezni, hogy ez kell-e?
- [X] Fontos-e a fafaj?
- [X] Boxplot a nullára redukálást megvizsgálni, jó-e?
- [ ] A jelenlegi boxplotoknál a kezelésből vontuk ki a kontrollt. Van-e jelentősége?

* <2022-09-01 cs>
Zolival.
A centrált boxplotok jobban áttekinthetőek. Jó lesz.

4 oldalas kell. Mehet fafaj szerint. Tölgy eleve magasabb fekvésben.
Égeres mélyebb és magasabb fekvésben.

-100 - (-200) (kezelt, mínusz kontroll)
-100 - (-300)

- [ ] A kút adatok a tereptől vannak? Valószínűleg a terepre átszámolva küldte Kaszó.

** Újabb boxplot
Beavatkozási időszakból kivonni a kontrollt!

A különbségekre kell a t próba
Intervetnion - kontroll időszak. Ezt a t-próba csinálta.


** Ábrázolni
*** x tengely
Talajvízmélység 
*** y tengelyen.
Beavatkozás hatása (intervention impact) 
Ez az Intervention - kontroll értékek!

Kis boxplotok az ábrán. Még egy grafikon.
Mérőhelyenként egy kupac.

** Trend
Kontrollkutak átlaga és hogyan változik?


Mondta Andrásnak, hogy kell egy hosszú távú talajvíz adatsor.
Amit a vizig mért. A területen mi következett be? Jellemző kutat.
Valahol látott (valamijen jelentésben) egy hosszútávú idősort.

Horváth Laci társszerző és telefon a taljvízkúttól.
Van-e hosszú távú adat. Vízügyes Baláta-tó melletti kút.
Észak felé folyik. Koordinátáit megmondja.

* <2022-09-01 cs> Csáki Peti kutak
Megírta a kút adatigénylés adatait.

* <2022-09-05 h>
Andrissal beszéltünk, hogy nézze meg az adatigénylést.

* <2022-09-15 cs>
- [X] Andris megnézi az ábra méreteket.

- [X] Boxplot nullára húzva a teljes időszakra méret! 15 cm széles
- [ ] Boxplot nullára húzva a vegetációs időszakra
- [ ] Táblázat az adatokból t-próbával.

* <2022-10-02 v>
Bocsánat, hogy megkésve, de idézem az insturction-ból a
követelményeket a JH&HM figures-ra kigyűjteni.

Figures should be informative, attractive and readable. Design them to
fit either into 1 column (8.6 cm), intermediate width (12 cm) or to
the width of the page (17.8 cm). At this print size, the photographs
should have a minimum resolution 300 dpi, bitmapped graphs and
drawings 1000 dpi, combinations of photographs and drawings 500
dpi. Vector drawings should contain all the used fonts and the minimum
line thickness should be 0.25 pt. Avoid any large size differences of
the numbers, letters and symbols used within the figure. They must be
sufficiently large such that they are at least 1.5 mm high in final
printed form. Do not hide unwanted data in masks or layers. Do not use
outer boxes or frames. Each figure with the figure caption should be
arranged on a separate page at the end of the manuscript. After
accepting the paper for publication, the figures should be submitted
in TIFF, JPEG, EMF, WMF or MS Office files.

* <2022-10-07 p> Kútszint a felszíntől
Zoli videóüzenetéből vett utasítás alapján a felszíntől kell a talajvízszint.
* <2022-11-04 p> 
-boxplot

Beavatkozási időszakban lejjebb van.

kontroll - kezelt negatív. Ha lejjebb megy

Videófelvétel az ábrák gyártásáról
* <2022-11-07 h>
Meteorológia importja és ábrásítása.

* <2022-11-10 cs>
Ez az ábra kellene még R-ből! :)
A 9. és a 18. kút van megjelenítve.b

* <2023-02-09 cs>

Jellemző talajvíz mélység a felszíntől (az egész időszakra a kezelésnek a jellemzője) és
a különbség Befor-after közötti egy grafikonba! A boxplot mediánjainak a különbsége mehet.
delta-delta. Az lesz negatív is. Fafajok elkülönültek. Excelben is van!

Teljes időszakra és vegetációs időszakra.

* <2023-02-13 h>
Szépek lettek az ábrák! Meg kell nézni majd mi a különbség a teljes
időszakhoz képest.

A Summary pointsnál a függyőleges tengely nem fordítva van (mármint a
különbségek inkább pozitívak legyenek ha talajvízszint emelkedés
van). lehet csinálni boxlplotokat a szöveg mellé vagy ha az nem OK,
egy pontot mediánként.

Az ábrához javításként: After - before van és talajvíz mélység pozitívnak értelmezett!

* <2023-02-23 cs>

A Boxplotos ábrákhoz (mindkettőhöz a teljes és a vegetációs időszakhoz
is) gondoltam statisztikát a kék és a zöld ábrákkal jelölt eloszlások
közötti összehasonlításra. Ha t-próba nem jó akkor valami más.

Beszéltünk már róla, hogy ez így nem biztos, hogy szabályos de valami
különbség szignifikancia kellene a kontrol és a beavatkozással
érintett időszakok között, a kontrol kutak és a beavatkozással
érintett kutak térbeli külömbségének időbeli változását kimutatva.

* <2023-02-25 szo>
Péter, mielőtt még statisztikáznál "R"-be, felmerült egy kérdésem, de lehet csak belekavarodtam. És bízom benn, hogy Jobban vagy!
Katit is bevonom, hátha ő veszi észre a kérdésemre a választ! 😎

Zoli! Kérlek jól rágjuk át ezt most, Légyszíves alaposan nézd, mert akkor bukik a többi, ha itt baki van!!!!

kép.png

Az ábra mellett a kommentbe: próbáltam minden variációt végigfuttatni. Nézzétek majd meg, hogy nem számoltam e félre, előfordulhat!!!
Tehát kezdődik ott egy elágazás, hogy Sampling (mintavételi kút) - Control (kontroll kút).

Amit pirossal bejelöltem:
Az eredményeik így: +9, +16 VAGY -9, -16


Eddig AZONBAN e mentén haladtunk:
kép.png
AZÉRT (ha nem értettem félre), hogy nagyobb pozitív számot kapjunk az impactra.

Kérdésem, hogy így mennyire van ez "rendben" a varriációk tükrében?!?!
Esetleg abszolút értéket valahova? Vagy nem kivonni, hanem összeadni?

Ami a boxplotton (teljes időszak, nem csak a vegetációs) Így jelenik meg (oké, ott mediánok vannak).
(A szóban forgó kútpáros pirossal bekeretezve)

kép.png

* <2023-02-28 k>
Zoli magyarázat: A multkori levélben írt feladat magyarázata:
Legyen benne a t-próba átlaga és a 95% konfidencia intervallum.

* <2023-03-09 cs>

Annyi észrevételem lenne, hogy a konfidenciaintervallumok estében is
most a pozitív hatások (mikor talajvízszint emelkedések vannak)
negatív számmal vannak jelölve és ez nem szerencsés, jobb lenne
előjelet cserélni.

* <2023-03-13 h>

Piros táblázat Fig. 5 után. Ezt a teljes és a vegetációs időszak
összevetésére Készítettem. A p.value diff a kettő különbsége.
Az Full és a Veget táblázatokban. Példa: a második sorban nem nulla egyik sem
6 vs. 18 kutak: 0.159 - 0.076 = 0.083.

A Full és Veget táblázatban a p.diff értékek nullái a kerekítés miatt nullák,
tulajdonképpen < 0.001-et lehetne ide írni.

A p-érték ha kicsi, akkor a null-hipotézis, az az a két várható érték
megegyezik fennálása esetén nagyon kicsi a valószínűsége, hogy a
mintához hasonló adat előáll.  Ez itt azt jelenti, hogy a kezelés és a
kontroll időszakok jelentősen külöböznek, amikor a p-érték kicsi.
Definíció szerűen: A p-érték annak a valószínűsége, hogy a
nullhipotézis (itt előtte és utánna azonosak a talajvízszintek)
fennálása esetén a véletlen játéka a nullhipotézisnek legalább annyira
ellentmondó mintát produkál, mint a ténylegesen megfigyelt minta.

meanBfr = a különbségek átlaga a kezelés előtt
meanAftr = a különbségek átlaga a kezelések után

A conf.int.lwr = a 95% konfidencia intervallum alsó határa
A conf.intupr = a 95%-os konfidencia intervallum felső határa
A fenti két érték között helyezkedik el nagy valószínűséggel (95%)
a különbség.

* <2023-12-18 h>
Gyakoriság-Tartósság

Talajvíz adatsorokra, konkrétan mit, elfelejtette.

Felhívja Zolit.
Mire kell a gyakoriság-tartósság görbe. Térbeli különbség.
Beavatkozás előttibe?
Maga sem tudja, hogy mi jön ki belőle. Kutat kiválasztani, ami jó, amit jobbnak
találtunk. Beavatkozás előtti, vagy utánni esetben mutat-e valamit?
Lehet-e bármit is mondani előtte. Nézzük meg, hátha látható valami.

* <2024-01-02 k>
Gy-T értelmezés.
SummaryPoints ábrát szétválogattuk.

Egyenesek rátéve.

* <2024-01-19 p>
Néztük az ábrával.
13 és 18-as kiválasztva.

** GY-T
Gyakoriság, tartósságnál a más színnel legyen mögötte a másik GY-T

Még különbség nem kell, úgy ábrázolni, hogy előtte és utána nem egy függvény az ábrán,
amiből egyik a kontroll (fekete) beavatkozás (piros)

13 és 18-ra.

** Továbfejlesztés
Boxplotok előtte és utánna.

Úgy kellene csinálni, hogy először kivonni a kezelt kútból a kontroll
kutat és különbség idősorra az előtte utána.

** Boxplotok
Azt mondák OK.

* <2024-04-04 cs>

Kell:
- napi csap,
- napi hőm,
- groundwater

(7naposra); 52 hét, vagyis 2 évra 104 adat.

Klímarezsimes felosztás pl. 3-4 havi részekre: csapadékos időszak ÉS vegetációs időszak. Vegetációs,
DE csapadék mentes időszak, ilyen felosztásba valószínűleg nem lenne korreláció, mert el van
választva, és ezekre a boxplotokat, és ezt összehasonlítani.
Vagy: selection of events. Pl. erősebb csapadékos időszakba – 7nap – nézzük a vízszintet
Ezeknél a lényeg, hogy ne Idősor szagú legyen a legfelső pontba leírtak miatt.
