* <2022-05-24 k>

Van sok kaszó által mért kút (18 kút) ebből 4 db kontroll.
Excellben látszik, amit Zoli küldött. Kézi észlelés, heti egy adat.
Van hozzá csapadék is. Nedves vagy száraz év, esett vagy nem esett.

Cél az, hogy a vízvisszatartás pozitív hatását számszerűsítsük.

2014 21. hét az első oszlop. Milyen nap?

2021. 40. héttől kezdődik.

** Feladat
- [X] Kontroll kutakat idősorként ábrázolni. Négy év adata.
  2014-től heti mérések, a második munkalapon már feliratozott.
- [X] Kitalálni, hogy hogyan nézzük meg.
- [X] Tölgyes és égeres kontroll meg kell felezni.
- [ ] Kitalálni, hogy milyen elrendezést lehet ráhúzni.

* Differenciás
Azonos fafajjal azonos talajvízmélységgel rendelkező kontrollt választasz a kontroll időszakban (2014/40. héttől, két év múlváig két vegetációs időszak, két év)
. Megvan az Excelben, hogy melyiket melyikhez választották.

Utánna különbségeket képzek a kontroll kút és a beavatkozással érintett kút között. Amikor megvan, akkor van egy különbség idősorom. Két kút különbség idősora.

A beavatkozásos időszakban is meg kell csinálni ugyanezt. Ezzel a meteorológiai hatásokat kiejtetted. Mivel nem nagy távolságok, nagyjából ugyan az.
A vegetáció hatását kiejted, mert ugyan abból az állományból van. A talajvíz hatása is kiejtve, mert ugyan az a mélység.

Úgy lett belőle egy-egy oszlop, hogy vettek belőle egy átlagot.


Különbség idősor a kontroll és a különbségidősor a beavatkozásosban. Ott lehet hatással a beavatkozás típusa és a beavatkozás hatása.
A távolság is.

A különbség idősorokat lehet elemezni a távolsággal.

Van két időszak, nem csak az átlagait, hanem a térbeli idősoroknak az időbeli különbségét hasonítod össze.

Tavak hatása sokkan nagyobb, mint a logveirnek. Teljes időszakra és a vegetációs időszakra.

Különbség idősor, amin nincs beavatkozás, különbség idősor, amin van beavatkozás.

boxplotként a diagramban, ami tulajdonképpen a térbeli és időbeli különbségek átlaga.

Térbeli különbség kontrol vs. kezelés (de akkor még nincs kezelés)
Időbeli, amikor a térkbeli idősor különbségét vettem, akkor veszem a két eredmény különbségét.

Van róla rajz.

* <2022-06-20 h>

** Idősor ábrák
- [X] Összes kontroll
- [X] Összes éger
- [X] Összes tölgy

** Differencia
Táblázat alapján, majd küldi.
Különbségek, kontroll/kezelés.

Különbségek boxplot ábra.
Két részben 2016-10-01 előtt és után.

* Kérdések
Távoli kutak (3&4) hol vannak az áttekintő ábráról. Kívül esnek a területen?
Jó-e a tábla?

* <2022-08-18 cs>
Csoportokba sorolt kutak.

- Kontroll
- Égeres
- Tölgyes

A számítás nem volt jó, az alapadatok jók voltak. Az Előd rosszból
vonogatott ki.

Idősorokból kell ábra. A csapadék idősort is rá kell tenni.
Az elején csinált András havi csapadékokat.

A kiinduló táblázatban van heti csapadékösszeg és
András megnézni, hogy mi van nálla. Kiss Katival letöltött
Boreas adatok?

A kút száma lehetne a közös hivatkozási alap.
Az Erdészettudomány Közlemények cikk alapján megnézni.

Koordináták a monitoring tervben. 3. fejezetben
Adatok/Kaszozrt/monitoring terv

Olyan plotokat kellene létrehozni

** Ábrák
*** Áttekintő
4-es ábra, ahol a kontroll és a többi csoportosan látszik.
4 ábra egymás mellett idősorosan.

*** Szemléltető ábra
Hasonló az Elődéhez szemléltető ábra. Hogyan lehetnek a különbségek.
Különböző színnel beszinezni a különbségeket a 2. ábrán.

*** Boxplot
Táblázatba szedni a boxplot adatait.

*** t-próba
t-próbával összehasonlítani a két adatsort.
Van-e szignifikáns különbség

*** Vegetációs időszakra
Csak a vegetációs időszakra.

Cseke Csabának a dolgozatában bent vannak a leürítések.

Okt1–Szept30 nemzetközi hidro év. Erre kell minden az ábrára!

Vegetációs időszak Április1–Szept30-ig.

*** Táblázat
Pontszám átlag, szórás, db.

* <2022-08-20 szo>
** Boxplothoz ötlet
Egy objektumba rakni minden adatot.
Esetleg összehasonlítható, ha nullába transzformálom az alapesetet.

* <2022-08-23 k>
A Control & Treatment különböző színű.

Jó ábra helye
/KOrabbi_anyagok_legbővebben_CsekeCsabaSzakdolgozat/Adat
ok/Kaszo_Elod_EGU2019joo/Plot.xlsx

Az a jó, ha feljebb van a kezelés boxplotja!

A kutakat a log weir és a reservoir alapján csoportosítani!

Kell egy olyan magyarázó ábra, ami a műveletet magyarázza.

Van napi csapadék.

** Kérdések
- [X] 4 részes idősor ábra csapadékkal, a nyers adatok bemutatására. Zolitól kérdezni, hogy ez kell-e?
- [X] Fontos-e a fafaj?
- [X] Boxplot a nullára redukálást megvizsgálni, jó-e?
- [ ] A jelenlegi boxplotoknál a kezelésből vontuk ki a kontrollt. Van-e jelentősége?

* <2022-09-01 cs>
Zolival.
A centrált boxplotok jobban áttekinthetőek. Jó lesz.

4 oldalas kell. Mehet fafaj szerint. Tölgy eleve magasabb fekvésben.
Égeres mélyebb és magasabb fekvésben.

-100 - (-200) (kezelt, mínusz kontroll)
-100 - (-300)

- [ ] A kút adatok a tereptől vannak? Valószínűleg a terepre átszámolva küldte Kaszó.

** Újabb boxplot
Beavatkozási időszakból kivonni a kontrollt!

A különbségekre kell a t próba
Intervetnion - kontroll időszak. Ezt a t-próba csinálta.


** Ábrázolni
*** x tengely
Talajvízmélység 
*** y tengelyen.
Beavatkozás hatása (intervention impact) 
Ez az Intervention - kontroll értékek!

Kis boxplotok az ábrán. Még egy grafikon.
Mérőhelyenként egy kupac.

** Trend
Kontrollkutak átlaga és hogyan változik?


Mondta Andrásnak, hogy kell egy hosszú távú talajvíz adatsor.
Amit a vizig mért. A területen mi következett be? Jellemző kutat.
Valahol látott (valamijen jelentésben) egy hosszútávú idősort.

Horváth Laci társszerző és telefon a taljvízkúttól.
Van-e hosszú távú adat. Vízügyes Baláta-tó melletti kút.
Észak felé folyik. Koordinátáit megmondja.

* <2022-09-01 cs> Csáki Peti kutak
Megírta a kút adatigénylés adatait.

* <2022-09-05 h>
Andrissal beszéltünk, hogy nézze meg az adatigénylést.

* <2022-09-15 cs>
- [ ] Andris megnézi az ábra méreteket.

- [X] Boxplot nullára húzva a teljes időszakra méret! 15 cm széles
- [ ] Boxplot nullára húzva a vegetációs időszakra
- [ ] Táblázat az adatokból t-próbával.

* <2022-10-02 v>
Bocsánat, hogy megkésve, de idézem az insturction-ból a
követelményeket a JH&HM figures-ra kigyűjteni.

Figures should be informative, attractive and readable. Design them to
fit either into 1 column (8.6 cm), intermediate width (12 cm) or to
the width of the page (17.8 cm). At this print size, the photographs
should have a minimum resolution 300 dpi, bitmapped graphs and
drawings 1000 dpi, combinations of photographs and drawings 500
dpi. Vector drawings should contain all the used fonts and the minimum
line thickness should be 0.25 pt. Avoid any large size differences of
the numbers, letters and symbols used within the figure. They must be
sufficiently large such that they are at least 1.5 mm high in final
printed form. Do not hide unwanted data in masks or layers. Do not use
outer boxes or frames. Each figure with the figure caption should be
arranged on a separate page at the end of the manuscript. After
accepting the paper for publication, the figures should be submitted
in TIFF, JPEG, EMF, WMF or MS Office files.

* <2022-10-07 p> Kútszint a felszíntől
Zoli videóüzenetéből vett utasítás alapján a felszíntől kell a talajvízszint.
